# **Rodrigo Hodgson - RA 911134**

In [121]:
print('Meu nome é: Rodrigo Hodgson')

Meu nome é: Rodrigo Hodgson


##Exercício A0.1

Quantos operações de ponto flutuante (flops) de soma e de multiplicação tem a multiplicação matricial $AB$, sendo que a matriz $A$ tem tamanho $m \times n$ e a matriz $B$ tem tamanho $n \times p$?

Resposta:
- número de somas: **(n-1).m.p (são n-1 somas para cada elemento da matriz m x p resultante)**
- número de multiplicações: **n.m.p (são n multiplicações para cada elemento da matriz m x p resultante)**

## Exercício A0.2

Em programação matricial, não se faz o loop em cada elemento da matriz,
mas sim, utiliza-se operações matriciais.

Dada a matriz `A` abaixo, calcule a média dos valores de cada linha sem utilizar laços explícitos.

Utilize apenas a biblioteca numpy.

In [122]:
import numpy as np

In [123]:
A = np.arange(24).reshape(4, 6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [124]:
A.mean(1)

array([ 2.5,  8.5, 14.5, 20.5])

## Exercício A0.3

Seja a matriz $C$ que é a normalização da matriz $A$:
$$ C(i,j) = \frac{A(i,j) - A_{min}}{A_{max} - A_{min}} $$

Normalizar a matriz `A` do exercício acima de forma que seus valores fiquem entre 0 e 1.

In [125]:
from numpy.core.fromnumeric import amin
AMAX = A.max(0).max(0)
AMIN = A.min(0).min(0)
CN = np.subtract (A,AMIN)
CD = np.subtract (AMAX,AMIN)
C = np.divide (CN,CD)
print (C)

[[0.         0.04347826 0.08695652 0.13043478 0.17391304 0.2173913 ]
 [0.26086957 0.30434783 0.34782609 0.39130435 0.43478261 0.47826087]
 [0.52173913 0.56521739 0.60869565 0.65217391 0.69565217 0.73913043]
 [0.7826087  0.82608696 0.86956522 0.91304348 0.95652174 1.        ]]


## Exercício A0.4

Modificar o exercício anterior de forma que os valores de cada *coluna* da matriz `A` sejam normalizados entre 0 e 1 independentemente dos valores das outras colunas.


In [126]:
CMAX = A.max(0)
CMIN = A.min(0)
AUX = np.array([[1],[1],[1],[1]])
MMIN = np.multiply(AUX,CMIN)
MMAX = np.multiply (AUX,CMAX)
CN = np.subtract (A,MMIN)
CD = np.subtract(MMAX, MMIN)
C = np.divide (CN,CD)
print (C)

[[0.         0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]
 [1.         1.         1.         1.         1.         1.        ]]


## Exercício A0.5

Modificar o exercício anterior de forma que os valores de cada *linha* da matriz `A` sejam normalizados entre 0 e 1 independentemente dos valores das outras linhas.


In [127]:
CMAX = A.ptp(1)
CMIN = A.min(1)
AUX = np.array([[1],[1],[1],[1],[1],[1]])
MMIN = np.multiply(CMIN,AUX)
MMAX = np.multiply (CMAX,AUX)
CN = np.subtract (A.T,MMIN)
C = np.divide (CN,MMAX).T
print (C)

[[0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]]


## Exercício A0.6

A [função softmax](https://en.wikipedia.org/wiki/Softmax_function) é bastante usada em apredizado de máquina para converter uma lista de números para uma distribuição de probabilidade, isto é, os números ficarão normalizados entre zero e um e sua soma será igual à um.

Implemente a função softmax com suporte para batches, ou seja, o softmax deve ser aplicado a cada linha da matriz. Deve-se usar apenas a biblioteca numpy. Se atente que a exponenciação gera estouro de representação quando os números da entrada são muito grandes. Tente corrigir isto.

In [128]:

from numpy.lib.index_tricks import CClass
import numpy as np


def softmax(A):
    '''
    Aplica a função de softmax à matriz `A`.

    Entrada:
      `A` é uma matriz M x N, onde M é o número de exemplos a serem processados
      independentemente e N é o tamanho de cada exemplo.
    
    Saída:
      Uma matriz M x N, onde a soma de cada linha é igual a um.
    '''
    CMAX = A.ptp(1)
    CMIN = A.min(1)
    TAMAUX = np.size(A,0)
    AUX = np.repeat(1,TAMAUX,axis=0).T
    MMIN = np.multiply(CMIN,AUX)
    MMAX = np.multiply (CMAX,AUX)
    CN = np.subtract (A.T,MMIN)
    C = np.divide (CN,MMAX)
    SOMA= sum(C)
    MPAD = np.multiply(SOMA,AUX)
    D = np.divide (C,MPAD).T
    return D
    

Mostre que sua implementação está correta usando uma matriz pequena como entrada:

In [129]:
A = np.array([[0.5, -1, 1000],
              [-2,   0, 0.5]])
softmax(A)

array([[0.00149626, 0.        , 0.99850374],
       [0.        , 0.44444444, 0.55555556]])

O código a seguir verifica se sua implementação do softmax está correta. 
- A soma de cada linha de A deve ser 1;
- Os valores devem estar entre 0 e 1

In [130]:
np.allclose(softmax(A).sum(axis=1), 1) and softmax(A).min() >= 0 and softmax(A).max() <= 1

True

Mostre que sua implementação é eficiente usando uma matriz grande como entrada:

In [131]:
A = np.random.uniform(low=-10, high=10, size=(128, 100_000))

In [132]:
%%timeit
softmax(A)

1 loop, best of 5: 171 ms per loop


In [133]:
SM = softmax(A)
np.allclose(SM.sum(axis=1), 1) and SM.min() >= 0 and SM.max() <= 1

True

## Exercício A0.7

Implemente uma classe que normalize um array de pontos flutuantes `array_a` para a mesma média e desvio padrão de um outro array `array_b`, conforme exemplo abaixo:
```
array_a = np.array([-1, 1.5, 0])
array_b = np.array([1.4, 0.8, 0.3, 2.5])
normalize = Normalizer(array_b)
normalized_array = normalize(array_a)
print(normalized_array)  # Deve imprimir [0.3187798  2.31425165 1.11696854]
```

In [ ]:
# Escreva seu código aqui.

Mostre que seu código está correto com o exemplo abaixo:

In [ ]:
array_a = [-1, 1.5, 0]
array_b = [1.4, 0.8, 0.3, 2.5]
normalize = Normalizer(array_b)
normalized_array = normalize(array_a)
print(normalized_array)

##Exercício A0.8

Qual o custo (entropia cruzada) esperado para um exemplo (uma amostra) no começo do treinamento de um classificador inicializado aleatoriamente?

A equação da entropia cruzada é:
$$L = - \sum_{j=0}^{K-1} y_j \log p_j, $$
Onde:

- K é o número de classes;

- $y_j=1$ se $j$ é a classe do exemplo (ground-truth), 0 caso contrário. Ou seja, $y$ é um vetor one-hot;

- $p_j$ é a probabilidade predita pelo modelo para a classe $j$.

A resposta tem que ser em função de uma ou mais das seguintes variáveis:

- K = número de classes

- B = batch size

- D = dimensão de qualquer vetor do modelo

- LR = learning rate

Resposta:

Fim do notebook.